[package]
name = "soundkit-aac"
version = "0.12.3"
edition = "2021"
readme = "README.md"
repository = "https://github.com/wavey-ai/soundkit"

[dependencies]
access-unit = { git = "https://github.com/wavey-ai/access-unit.git" }
fdk-aac = { git = "https://github.com/wavey-ai/fdk-aac-rs.git", optional = true }
soundkit-audio-demux = { path = "../soundkit-audio-demux", default-features = false, features = ["mp4"], optional = true }

soundkit = { path = "../soundkit" }
tracing = "0.1.40"

[features]
default = ["fdk"]
fdk = ["fdk-aac"]
mp4-demux = ["soundkit-audio-demux"]
mp4-decoder = ["fdk-aac", "mp4-demux"]

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
mp4 = "0.14.0"
