[package]
name = "soundkit-codec-fate"
version = "0.13.3"
edition = "2021"
publish = false

[dependencies]
frame-header = "0.2.2"
sha2 = "0.10"
soundkit = { path = "../soundkit", version = "0.13.3" }
soundkit-aac-lc = { path = "../soundkit-aac-lc", version = "0.13.3" }
soundkit-decoder = { path = "../soundkit-decoder", version = "0.13.3" }
soundkit-video = { path = "../soundkit-video", version = "0.13.3" }
