/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmaudiocontentcipher_free: (a: number, b: number) => void;
export const __wbg_wasmaudiocontentkeyunwrapper_free: (a: number, b: number) => void;
export const __wbg_wasmmusicdecoder_free: (a: number, b: number) => void;
export const __wbg_wasmsoundkitframedecoder_free: (a: number, b: number) => void;
export const buildAudioGroupAssociatedData: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number) => [number, number, number];
export const buildSoundKitFrameHeaderV2: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const buildSoundKitFrameV2: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number];
export const wasmaudiocontentcipher_new: (a: number, b: number) => [number, number, number];
export const wasmaudiocontentcipher_open: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const wasmaudiocontentcipher_seal: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number];
export const wasmaudiocontentkeyunwrapper_new: (a: number, b: number) => [number, number, number];
export const wasmaudiocontentkeyunwrapper_open: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const wasmaudiocontentkeyunwrapper_seal: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const wasmmusicdecoder_flush: (a: number) => [number, number, number];
export const wasmmusicdecoder_new: () => number;
export const wasmmusicdecoder_newRawLinear16: (a: number, b: number) => [number, number, number];
export const wasmmusicdecoder_newRawLinear32: (a: number, b: number) => [number, number, number];
export const wasmmusicdecoder_newWithFormat: (a: number, b: number) => [number, number, number];
export const wasmmusicdecoder_push: (a: number, b: number, c: number) => [number, number, number];
export const wasmsoundkitframedecoder_bufferedBytes: (a: number) => number;
export const wasmsoundkitframedecoder_clearKey: (a: number) => void;
export const wasmsoundkitframedecoder_finish: (a: number) => [number, number];
export const wasmsoundkitframedecoder_new: () => number;
export const wasmsoundkitframedecoder_newWithDecimalKey: (a: number, b: number) => [number, number, number];
export const wasmsoundkitframedecoder_newWithKeyBytes: (a: number, b: number) => [number, number, number];
export const wasmsoundkitframedecoder_push: (a: number, b: number, c: number) => [number, number, number];
export const wasmsoundkitframedecoder_reset: (a: number) => void;
export const wasmsoundkitframedecoder_setDecimalKey: (a: number, b: number, c: number) => [number, number];
export const wasmsoundkitframedecoder_setKeyBytes: (a: number, b: number, c: number) => [number, number];
export const wasmmusicdecoder_newAuto: () => number;
export const wasmsoundkitframedecoder_newUnencrypted: () => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
